# .travis.yml

language:
   - go

os: 
   - windows
   - linux
   - osx

git:
   depth: 1

before_script:
   - git config --global user.name sndnvaps
   - git config --global user.email sndnvaps@gmail.com

script:
   - if [ "$TRAVIS_OS_NAME" = "linux"]; then GOOS=linux  GOARCH=amd64 go build -o ebookdownloader-linux-amd64
   - if [ "TRAVIS_OS_NAME" = "osx"]; then GOOS=darwin GOARCH=amd64 go build -o ebookdownloader-darwin-amd64
   - if [ "TRAVIS_OS_NAME" = "windows"]; then GOOS=windows GOARCH=amd64 go build -o ebookdownloader-windows-amd64.exe

after_success:
   - if [ "$TRAVIS_OS_NAME" = "linux"]; then 7z a -tzip ebookdownloader-linux-amd64.zip tools/kindlegenLinux tpls/*  LICENSE README.md ebookdownloader-linux-amd64
   - if [ "TRAVIS_OS_NAME" = "osx"]; then 7z a -tzip ebookdownloader-darwin-amd64.zip tools/kindlegenMac tpls/* LICENSE README.md ebookdownloader-darwin-amd64
   - if [ "TRAVIS_OS_NAME" = "windows"]; then 7z a -tzip ebookdownloader-windows-amd64.zip tools/kindlegen.exe tpls/* LICENSE README.md ebookdownloader-windows-amd64
